name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.6", "3.11","3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6

      - name: Setup env
        run: |
          echo "${{secrets.ENV_VARS}}" > .env

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requires.txt
          pip install pytest
          pip install python-dotenv

      - name: Lib setup for testing
        run: |
           python -m setup develop
           rm -rf app.egg-info

      - name: Running authorization tests
        run: pytest tests/auth 

      - name: Running server tokens generation tests
        run: pytest tests/server_tokens --no-header --no-summary -q

      - name: Running third parties integration tests
        run: pytest tests/third_parties --no-header --no-summary -q

      - name: Running image generation tests
        run: pytest tests/generate --no-header --no-summary -q


      - name: Running Redis caching tests
        run: pytest tests/cache --no-header --no-summary -q
