name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up .env
        run: |
           echo '${{ secrets.ENV_VARS }}' >> msrv/lib/env.py

      - name: Setup poetry
        run: |
            python -m pip install --upgrade pip
            python -m pip install poetry

      - name: Configure poetry
        run: poetry config virtualenvs.create false
      - name: Install deps
        run: poetry install
      - name: Install dev deps
        run: pip install -r scripts/requires.dev.txt
      - name: Running tests
        run: pytest
